name: Documents

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.18

      # https://github.com/actions-rs/toolchain/issues/110
      - name: Read rust-toolchain.toml
        id: rust-toolchain
        run: |
          awk -F= '/channel/{channel=gsub("\"","",$2);printf "::set-output name=channel::%s\n", $channel}' rust-toolchain.toml

      - name: Set up Rust Nightly
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ steps.rust-toolchain.outputs.channel }}
          components: rustfmt, clippy

      - name: Rust Cache
        uses: Swatinem/rust-cache@v1.4.0

      - name: Run eBPF toolchain setup
        run: |
          make -C bpf setup
          cd bpf && cargo check

      - name: Install LLVM and libbpf dependencies
        run: sudo apt-get update -y && sudo apt-get install llvm libelf-dev

      - name: Initialize and update libbpf submodule
        run: git submodule init && git submodule update

      - name: Set up Jsonnet
        run: ./env.sh

      - name: Build
        run: make bpf build

      - name: Docs check
        run: |
          make README.md
          git diff --exit-code ':!deploy'
